### PR TITLE
resolve #11

### LINKED ISSUE #11: Add binary files/bin directory to git ignore
Please remember to remove /bin from repository

### PR DESCRIPTION
**Pull request by mBialczak**
1. physically removed "bin" directory from repo
2. added "bin" directory to .gitignore
3. updated Dockerfile in order to have ready-accessible built UT target via docker
4. Removed explicit unit-test step: 
    RATIONALE: there is no longer a pre-built bin directory so the step would fail.
    The docker build image already contains UT run, so there is no additional need to run tests separately.
image

### CODE REVIEW

**Comment by mBialczak** [comment]
Do we accept unit-test step removal and is docker file ut-run enough for us?
If not, I could use some help to resolve the problem of building the binary on CI, running tests, as I faced some problems with that

**Comment by ziobron** [comment]
Thanks @fbtom for Code Review.
🏅 1 XP granted

**Comment by ziobron** [comment]
Your PR was merged!
🏅 2 XP granted. Thanks @mBialczak for making course materials better!

**Review by BaqWin — COMMENTED** [review]
Ok

**Comment by ziobron** [comment]
Thanks @BaqWin for Code Review.
🏅 1 XP granted

**Pull request merged**
