### PR TITLE
fix-typo: one letter typo fix in README

### PR DESCRIPTION
**Pull request by mBialczak**

### CODE REVIEW

**Review by Aleksiiej — COMMENTED** [review]
Because preview there was Alpine Linux, and it has ash, not bash, and I didn't make correction.

**Comment by ziobron** [comment]
Thanks @Aleksiiej for Code Review.
🏅 1 XP granted

**Review by Aleksiiej — APPROVED** [review]

**Comment by ziobron** [comment]
Thanks @Aleksiiej for Code Review.
🏅 1 XP granted

**Comment by ziobron** [comment]
Your PR was merged!
🏅 2 XP granted. Thanks @mBialczak for making course materials better!

**Pull request merged**
