### PR TITLE
Issue #29: Adjust clang-format

### PR DESCRIPTION
**Pull request by fbtom**
Issue #29

Removed erronous lines from .clang-format
Clang-formatted cpp files.
Added EOF lines.

### CODE REVIEW

**Review by mBialczak — APPROVED** [review]

**Comment by ziobron** [comment]
Thanks @mBialczak for Code Review.
🏅 1 XP granted

**Review by BaqWin — APPROVED** [review]
Looks good

**Comment by ziobron** [comment]
Thanks @BaqWin for Code Review.
🏅 1 XP granted

**Comment by ziobron** [comment]
Your PR was merged!
🏅 2 XP granted. Thanks @fbtom for making course materials better!

**Pull request merged**
